site_name: Geoladris - Core
pages:
- Home: index.md
- 'Change log': changelog.md
- 'Directorio de configuración': conf_dir.md
- 'Minificando Javascript y CSS': minify_js_css.md
- 'Plugins': plugins.md
- 'Configuración de Travis': travis.md

